theme: jekyll-theme-minimal
title: Anni's Github Page
logo: https://media-exp1.licdn.com/dms/image/C4E03AQEYKOBH_45Hrg/profile-displayphoto-shrink_800_800/0/1606363450212?e=1634169600&v=beta&t=4TqZgdpBigFlhBV0s3QHGRmudOpGJIBOV_OXLaCWQDU
description: Anni Homepage for personal and social purposes
